# Pretty simple docker-compose setup here. Currently only targetting the db, but will expand out to include the app and web services in the future.
version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: felsic-mongodb
    restart: always
    ports:
      - "27017:27017"
      #   volumes:
      #     - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

